const Data = {
  productItems: [
    {
      id: 1,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      cover2: "./images/flash/flash-2.png",
      cover3: "./images/flash/flash-3.png",
      cover4: "./images/flash/flash-4.png",
      description: "Description of the shoes product is the best things you have.",
      name: "Shoes",
      price: 100,
      
    },
    {
      id: 2,
      discount: 40,
      cover: "./images/flash/flash-2.png",
      cover2: "./images/flash/flash-1.png",
      cover3: "./images/flash/flash-3.png",
      cover4: "./images/flash/flash-4.png",
      description: "Description of the shoes product is the best things you have.",
      name: "Watch",
      price: 20,
    },
    {
      id: 3,
      discount: 40,
      cover: "./images/flash/flash-3.png",
      cover2: "./images/flash/flash-2.png",
      cover3: "./images/flash/flash-1.png",
      cover4: "./images/flash/flash-4.png",
      description: "Description of the shoes product is the best things you have.",
      name: "Smart Mobile Black",
      price: 200,
    },
    {
      id: 4,
      discount: 40,
      cover: "./images/flash/flash-4.png",
      cover2: "./images/flash/flash-2.png",
      cover3: "./images/flash/flash-1.png",
      cover4: "./images/flash/flash-3.png",
      description: "Description of the shoes product is the best things you have.",
      name: "Smart Watch Black",
      price: 50,
    },
    {
      id: 5,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      cover2: "./images/flash/flash-2.png",
      cover3: "./images/flash/flash-3.png",
      cover4: "./images/flash/flash-4.png",
      description: "Description of the shoes product is the best things you have.",
      name: "Shoes",
      price: 100,
    },
    {
      id: 6,
      discount: 50,
      cover: "./images/flash/flash-3.png",
      cover2: "./images/flash/flash-2.png",
      cover3: "./images/flash/flash-1.png",
      cover4: "./images/flash/flash-4.png",
      description: "Description of the shoes product is the best things you have.",
      name: "Shoes",
      price: 100,
    },
  ],
}
export default Data
