const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/shops-1.png",
      cover2: "./images/shops/shops-2.png",
      cover3: "./images/shops/shops-3.png",
      cover4: "./images/shops/shops-5.png",
      des: "5une in to the Make it Big Podcast — our thought leadership audio series for retailers, entrepreneurs and ecommerce professionals. You'll get expert insights, strategies and tactics to help grow your business.",
      name: "Mapple Earphones",
      price: "180",
      discount: "25",
    },
    {
      id: 8,
      cover: "./images/shops/shops-2.png",
      cover2: "./images/shops/shops-2.png",
      cover3: "./images/shops/shops-3.png",
      cover4: "./images/shops/shops-5.png",
      des: "5une in to the Make it Big Podcast — our thought leadership audio series for retailers, entrepreneurs and ecommerce professionals. You'll get expert insights, strategies and tactics to help grow your business.",
      name: "Vivo android one",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: "./images/shops/shops-3.png",
      cover2: "./images/shops/shops-2.png",
      cover3: "./images/shops/shops-3.png",
      cover4: "./images/shops/shops-5.png",
      des: "5une in to the Make it Big Podcast — our thought leadership audio series for retailers, entrepreneurs and ecommerce professionals. You'll get expert insights, strategies and tactics to help grow your business.",
      name: "Sony Light",
      price: "20",
      discount: "50 ",
    },
    {
      id: 10,
      cover: "./images/shops/shops-4.png",
      cover2: "./images/shops/shops-2.png",
      cover3: "./images/shops/shops-3.png",
      cover4: "./images/shops/shops-5.png",
      des: "5une in to the Make it Big Podcast — our thought leadership audio series for retailers, entrepreneurs and ecommerce professionals. You'll get expert insights, strategies and tactics to help grow your business.",
      name: "Iphone",
      price: "999",
      discount: "10 ",
    },
    {
      id: 11,
      cover: "./images/shops/shops-5.png",
      cover2: "./images/shops/shops-2.png",
      cover3: "./images/shops/shops-3.png",
      cover4: "./images/shops/shops-5.png",
      des: "5une in to the Make it Big Podcast — our thought leadership audio series for retailers, entrepreneurs and ecommerce professionals. You'll get expert insights, strategies and tactics to help grow your business.",
      name: "Ceats earphone",
      price: "80",
      discount: "20 ",
    },
    {
      id: 12,
      cover: "./images/shops/shops-7.png",
      cover2: "./images/shops/shops-2.png",
      cover3: "./images/shops/shops-3.png",
      cover4: "./images/shops/shops-5.png",
      des: "5une in to the Make it Big Podcast — our thought leadership audio series for retailers, entrepreneurs and ecommerce professionals. You'll get expert insights, strategies and tactics to help grow your business.",
      name: "Redimi Phone",
      price: "400",
      discount: "20 ",
    },
    {
      id: 13,
      cover: "./images/shops/shops-8.png",
      name: "Xeats earphones",
      price: "60",
      discount: "5 ",
    },
    {
      id: 14,
      cover: "./images/shops/shops-9.png",
      name: "Airpod",
      price: "120",
      discount: "10",
    },

  ],
}
export default Sdata
